/* 学习路线页的「Java 构造结构大全」：
   把每一种写法骨架（类、方法、字段、构造器、类型、集合 + 自定义类、Map 与 lambda）集中在一起，
   需要的地方直接照着抄骨架，能运行的示例都可以在页面里点「▶ 运行」看输出。 */
window.SYNTAX_MAP = {
  title: 'Java 构造结构大全（写法骨架 + 可运行示例）',
  intro: '把「各种构造」一次看全：类里能放什么、方法有几种写法、字段和构造器的全部形式、集合怎么装自己的类、Map 和 lambda / 方法引用怎么搭配。每段骨架都可以直接照抄改写，标注「可直接运行」的还能在页面里点一下看输出。',
  sections: [
    {
      id: 'class-anatomy',
      type: 'code',
      title: '① 类的完整构造：一个类里能放的所有成员',
      codeTitle: 'Student.java · 字段 / 静态块 / 实例块 / 构造器 / 方法 / 链式 / 泛型 / main',
      note: '按照从上到下的顺序看注释编号，就能知道自己写的类缺了什么。**这段可以直接运行**，运行结果写在末尾的注释里。',
      runnable: true,
      code: [
        'import java.util.ArrayList;      // 用到别的包里的类要 import（java.lang 下的不用）',
        '',
        '/**',
        ' * 一个「完整」的类骨架，可以照着这个顺序写自己的类：',
        ' * 字段 → 静态块 → 实例块 → 构造器 → 方法 → 重写 → 泛型方法 → main',
        ' */',
        'public class Student {',
        '',
        '    // ① 字段（属性）：[修饰符] 类型 名字 [= 初始值];',
        '    private String name;                      // 实例字段：每个对象一份，默认 null',
        '    private int score;                        // 默认 0',
        '    private static int count = 0;             // 静态字段：全类共享，用 类名.字段 访问',
        '    public static final int MAX_SCORE = 100;  // 常量：static + final，名字全大写',
        '',
        '    // ② 静态代码块：类第一次被加载时执行一次',
        '    static {',
        '        System.out.println("[加载] Student 类被加载了");',
        '    }',
        '',
        '    // ③ 实例代码块：每次 new 都执行，位置在构造器体之前',
        '    {',
        '        System.out.println("[初始化] 创建了一个对象");',
        '    }',
        '',
        '    // ④ 构造器：名字与类名相同、没有返回类型，可以重载',
        '    public Student() {',
        '        this("无名", 0);        // this(...) 调用本类另一个构造器，必须是第一行',
        '    }',
        '',
        '    public Student(String name, int score) {',
        '        this.name = name;       // this 用来区分同名的参数和字段',
        '        setScore(score);        // 构造器里也可以调用方法做校验',
        '        count++;                // 每 new 一个对象，静态计数器 +1',
        '    }',
        '',
        '    // ⑤ getter / setter：私有字段对外只留方法，这就是「封装」的入口',
        '    public String getName() {',
        '        return name;            // 最简单的构造：有返回类型就必须 return',
        '    }',
        '',
        '    public void setScore(int score) {',
        '        if (score < 0 || score > MAX_SCORE) {   // 入口先校验，防止脏数据',
        '            System.out.println("分数不合法：" + score);',
        '            return;                            // void 方法可以用 return 提前结束',
        '        }',
        '        this.score = score;',
        '    }',
        '',
        '    public int getScore() {',
        '        return score;',
        '    }',
        '',
        '    // ⑥ 静态方法：属于类，用 类名.方法() 调用，方法体里不能用 this',
        '    public static int getCount() {',
        '        return count;',
        '    }',
        '',
        '    // ⑦ 判断类方法：返回 boolean，名字习惯用 is / has / can 开头',
        '    public boolean isPass() {',
        '        return score >= 60;',
        '    }',
        '',
        '    // ⑧ 多个分支的返回值方法：每条路径都要 return',
        '    public String level() {',
        '        if (score >= 90) return "优秀";',
        '        if (score >= 75) return "良好";',
        '        if (score >= 60) return "及格";',
        '        return "不及格";',
        '    }',
        '',
        '    // ⑨ 重写 Object 的方法：打印对象时自动调用 toString()',
        '    @Override',
        '    public String toString() {',
        '        return name + "(" + score + "分)";',
        '    }',
        '',
        '    // ⑩ 链式方法：返回 this，就能连续调用 s.rename(..).setScore(..)',
        '    public Student rename(String newName) {',
        '        this.name = newName;',
        '        return this;',
        '    }',
        '',
        '    // ⑪ 泛型方法：<T> 写在返回类型前面，可处理任意元素类型',
        '    public static <T> void printAll(ArrayList<T> list) {',
        '        for (T item : list) System.out.println("  - " + item);',
        '    }',
        '',
        '    // ⑫ 入口方法：固定写法 public static void main(String[] args)',
        '    public static void main(String[] args) {',
        '        Student s = new Student("小明", 92);',
        '        s.rename("小明哥");              // 链式方法返回 this，可以接着调用',
        '        s.setScore(95);',
        '        System.out.println(s.getName() + " / " + s.getScore() + " / " + s.level() + " / 及格=" + s.isPass());',
        '        System.out.println("打印对象：" + s);',
        '        System.out.println("共创建 " + Student.getCount() + " 个对象，满分 " + Student.MAX_SCORE + " 分");',
        '',
        '        ArrayList<Student> list = new ArrayList<>();',
        '        list.add(s);',
        '        list.add(new Student("小红", 58));',
        '        System.out.println("名单：");',
        '        printAll(list);',
        '    }',
        '}',
        '',
        '/* ============ 运行结果 ============',
        '[加载] Student 类被加载了',
        '[初始化] 创建了一个对象',
        '[初始化] 创建了一个对象',
        '小明哥 / 95 / 优秀 / 及格=true',
        '打印对象：小明哥(95分)',
        '共创建 2 个对象，满分 100 分',
        '名单：',
        '  - 小明哥(95分)',
        '  - 小红(58分)',
        '================================== */'
      ].join('\n')
    },
    {
      id: 'member-table',
      type: 'table',
      title: '② 类里能放哪些成员（全部 9 种）',
      note: '一个类里能写的东西就这 9 种，看到陌生的写法时先判断它属于哪一类。',
      head: ['成员', '写法骨架', '说明'],
      rows: [
        ['实例字段', 'private String name = "默认值";', '每个对象一份；不写初始值时按类型给默认值（对象 null、int 0、boolean false）'],
        ['静态字段', 'private static int count = 0;', '全类共享一份，用 类名.字段 访问；第一次使用类时初始化'],
        ['常量', 'public static final int MAX = 100;', 'static + final，名字全大写；编译期就能确定值'],
        ['静态代码块', 'static { ... }', '类加载时执行一次，常用来初始化静态资源'],
        ['实例代码块', '{ ... }', '每次 new 都执行，且在构造器体之前；用得不多，新手容易看懵'],
        ['构造器', 'public Student(String name) { this.name = name; }', '名字=类名、没有返回类型；new 的时候调用'],
        ['实例方法', 'public String getName() { return name; }', '属于对象，能访问实例字段和静态字段'],
        ['静态方法', 'public static int getCount() { return count; }', '属于类，只能用 类名.方法()，方法体里没有 this'],
        ['内部类', 'static class Node { int v; }', '定义在类里面的类；加 static 的叫静态嵌套类，常见于工具类'],
        ['枚举 / 记录', 'enum Level { LOW, HIGH }　record Point(int x, int y) {}', 'JDK 5 / JDK 16 起支持；枚举是固定常量集合，record 是只装数据的不可变类'],
        ['注解类型', '@interface Author { String value(); }', '自定义注解，一般配合框架使用，入门阶段知道写法即可']
      ]
    },
    {
      id: 'method-forms',
      type: 'table',
      title: '③ 方法的全部写法（照着抄骨架）',
      note: '方法通用骨架：**[修饰符] 返回类型 方法名(参数类型 参数名) [throws 异常] { 方法体 }**。返回类型写 void 表示不返回结果；有返回类型时每条路径都要 return。',
      head: ['方法类型', '写法骨架', '说明'],
      rows: [
        ['最常见：getter', 'public String getName() { return name; }', 'private 字段的读取入口；只有一行 return 时也不用纠结'],
        ['setter', 'public void setName(String name) { this.name = name; }', 'void + this 区分同名参数和字段'],
        ['无参无返回', 'public void hello() { System.out.println("你好"); }', '只做事、不返回结果'],
        ['带参有返回', 'public int add(int a, int b) { return a + b; }', '最普通的方法构造'],
        ['布尔判断', 'public boolean isAdult() { return age >= 18; }', '名字习惯 is / has / can 开头'],
        ['多分支返回', 'public String level() { if (score >= 90) return "优秀"; return "一般"; }', '每个分支都要能 return，否则编译不过'],
        ['提前结束', 'public void check(int n) { if (n < 0) return; System.out.println(n); }', 'void 方法里 return; 用来提前退出'],
        ['静态方法', 'public static int max(int a, int b) { return a > b ? a : b; }', '工具方法首选；不能用 this、不能直接访问实例字段'],
        ['final 方法', 'public final void lock() { }', '子类不能重写它'],
        ['抽象方法', 'public abstract double area();', '只有声明没有方法体，写在抽象类/接口里，由子类实现'],
        ['接口默认方法', 'default String hello() { return "hi"; }', '接口里带方法体，实现类可以直接用'],
        ['接口静态方法', 'static Greeter of(String n) { return () -> n; }', '接口里的静态方法，用 接口名.方法() 调用'],
        ['可变参数', 'public static int sum(int... nums) { }', '类型... 名字，必须是最后一个参数；调用时可以传任意个'],
        ['泛型方法', 'public static <T> T first(List<T> list) { return list.get(0); }', '<T> 写在返回类型前面；调用时自动推断类型'],
        ['重载', 'add(int,int) 与 add(double,double)', '同名不同参数列表（个数/类型/顺序不同），与返回值无关'],
        ['重写', '子类 @Override 同名同参的方法', '父类引用调用时执行子类实现（多态）'],
        ['递归', 'static int f(int n) { return n <= 1 ? 1 : n * f(n - 1); }', '方法自己调用自己，必须有出口条件'],
        ['同步方法', 'public synchronized void add() { count++; }', '多线程下保证同一时刻只有一个线程进入'],
        ['链式方法', 'public Builder name(String n) { this.name = n; return this; }', '返回 this，调用方可以一路点下去'],
        ['入口方法', 'public static void main(String[] args) { }', '固定写法；数组参数用来接收命令行参数'],
        ['方法引用搭配', 'list.forEach(System.out::println);', '等价于 x -> System.out.println(x)；类型::实例方法 = 把参数当接收者']
      ]
    }
  ]
};
